export const DEFAULT_CATEGORIES = [
  { nom:'Alimentation', emoji:'🛒', couleur:'#D97706', type:'depense' },
  { nom:'Transport', emoji:'🚕', couleur:'#3B82F6', type:'depense' },
  { nom:'Logement', emoji:'🏠', couleur:'#DC2626', type:'depense' },
  { nom:'Factures', emoji:'💡', couleur:'#F59E0B', type:'depense' },
  { nom:'Santé', emoji:'❤️', couleur:'#EF4444', type:'depense' },
  { nom:'Éducation', emoji:'🎓', couleur:'#7C3AED', type:'depense' },
  { nom:'Loisirs', emoji:'🎮', couleur:'#EC4899', type:'depense' },
  { nom:'Shopping', emoji:'🛍', couleur:'#14B8A6', type:'depense' },
  { nom:'Télécommunication', emoji:'📱', couleur:'#6B7280', type:'depense' },
  { nom:'Voyage', emoji:'✈️', couleur:'#F97316', type:'depense' },
  { nom:'Salaire', emoji:'💰', couleur:'#16A34A', type:'revenu' },
  { nom:'Prime', emoji:'🏆', couleur:'#F59E0B', type:'revenu' },
  { nom:'Freelance', emoji:'💼', couleur:'#7C3AED', type:'revenu' },
  { nom:'Investissement', emoji:'📈', couleur:'#06B6D4', type:'revenu' },
  { nom:'Vente', emoji:'🛍️', couleur:'#EC4899', type:'revenu' },
  { nom:'Cadeau', emoji:'🎁', couleur:'#EC4899', type:'revenu' },
  { nom:'Remboursement', emoji:'🔄', couleur:'#14B8A6', type:'revenu' },
  { nom:'Autre', emoji:'📦', couleur:'#6B7280', type:'revenu' },
];
