import { Platform } from 'react-native';

export const Colors = {
  light: {
    background: '#F8F7FF',
    surface: '#FFFFFF',
    surfaceLight: '#F5F3FF',
    primary: '#7C3AED',
    primaryLight: '#A78BFA',
    text: '#1A153A',
    textSecondary: '#5D5780',
    textMuted: '#9590B0',
    textDisabled: '#C8C4DD',
    success: '#22C55E',
    successLight: '#34D399',
    danger: '#F43F5E',
    dangerLight: '#FB7185',
    info: '#33E1B7',
    warning: '#F59E0B',
    border: '#EDE9FE',
    bottomBar: '#FFFFFF',
    iaPurple: '#8B5CF6',
    iaBg: '#F5F3FF',
    icon: '#9590B0',
  },
  dark: {
    background: '#0F0B1F',
    surface: '#1D163A',
    surfaceLight: '#251C49',
    primary: '#7C3AED',
    primaryLight: '#9F67FF',
    text: '#FFFFFF',
    textSecondary: '#D5D2E8',
    textMuted: '#A29DBF',
    textDisabled: '#7F7A9D',
    success: '#22C55E',
    successLight: '#34D399',
    danger: '#F43F5E',
    dangerLight: '#FB7185',
    info: '#33E1B7',
    warning: '#F59E0B',
    border: 'rgba(255,255,255,0.06)',
    bottomBar: '#171030',
    iaPurple: '#8B5CF6',
    iaBg: '#261A4A',
    icon: '#A29DBF',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
